// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv7-a2UiZTvpaeIMyLtHFNmWlGMbNyLKc',
    appId: '1:648968745517:android:4dccb83493edb24ceefea4',
    messagingSenderId: '648968745517',
    projectId: 'mysentinal',
    storageBucket: 'mysentinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVryR6eOoCrk0V96VP4gt-ITWn_Rri28',
    appId: '1:648968745517:ios:30fc888d5781b8bdeefea4',
    messagingSenderId: '648968745517',
    projectId: 'mysentinal',
    storageBucket: 'mysentinal.appspot.com',
    androidClientId: '648968745517-6li61tvl0r1rleahbs0jie5bm7ae1vc7.apps.googleusercontent.com',
    iosClientId: '648968745517-ulq1mu5n1avti7ufd9926qj1kk6o5vkf.apps.googleusercontent.com',
    iosBundleId: 'com.technosphere.mysentinel',
  );

}